"""Provider-neutral helpers for exposing Protolink tools to LLM backends.

Protolink stores tool input schemas in a friendly flat parameter-map form. LLM
providers, however, expect JSON Schema objects or provider-specific function
declarations. This module converts the internal representation into canonical
schemas and builds the small synthetic tools used for agent delegation.
"""

from __future__ import annotations

import json
from dataclasses import dataclass, field
from typing import Any

from protolink.llms.actions import AgentCallAction, ToolCallAction
from protolink.tools import BaseTool

AGENT_INFER_TOOL_NAME = "protolink_delegate_agent"
AGENT_TOOL_CALL_TOOL_NAME = "protolink_call_agent_tool"


def _field(value: Any, name: str, default: Any = None) -> Any:
    """Read one field from either SDK objects or JSON dictionaries."""
    if isinstance(value, dict):
        return value.get(name, default)
    return getattr(value, name, default)


@dataclass
class ChatCompletionStreamAccumulator:
    """Accumulate one Chat Completions-style streamed tool call.

    OpenAI-compatible streaming APIs deliver tool calls as incremental deltas:
    the function name may appear in one event and argument JSON fragments in
    later events. This helper collects those fragments without depending on a
    specific SDK object type, then converts the completed call into the same
    Protolink action used by non-streaming adapters.
    """

    name: str | None = None
    arguments: list[str] = field(default_factory=list)

    def add_delta(self, tool_call_delta: Any) -> None:
        """Record one provider ``delta.tool_calls`` item."""
        function = _field(tool_call_delta, "function", {}) or {}
        name = _field(function, "name")
        if name:
            self.name = str(name)
        arguments = _field(function, "arguments")
        if arguments:
            self.arguments.append(str(arguments))

    def to_action(self) -> ToolCallAction | AgentCallAction | None:
        """Return the completed action, or ``None`` if no tool name arrived."""
        if not self.name:
            return None
        return native_tool_call_to_action(self.name, parse_json_arguments("".join(self.arguments) or "{}"))


def chat_completion_stream_delta(event: Any) -> tuple[str, list[Any]]:
    """Extract streamed text and tool-call deltas from one chat completion event."""
    choices = _field(event, "choices", []) or []
    if not choices:
        return "", []
    choice = choices[0]
    delta = _field(choice, "delta", {}) or {}
    content = _field(delta, "content") or ""
    tool_calls = _field(delta, "tool_calls", []) or []
    return str(content or ""), list(tool_calls)


def should_include_agent_tools(
    *,
    agent_callback_available: bool,
    agent_cards: list[Any] | None,
) -> bool:
    """Return whether native providers should expose agent delegation tools.

    Native tool-calling providers choose from the function declarations we send
    them. Exposing delegation functions without any discovered agent cards gives
    the model a callable surface with no valid targets, which is more confusing
    than the JSON path's ordinary self-correction. The synthetic agent tools are
    therefore available only when the runtime can dispatch them *and* the prompt
    contains at least one concrete agent for the model to choose.
    """
    return agent_callback_available and bool(agent_cards)


def normalize_tool_parameters(input_schema: dict[str, Any] | None) -> dict[str, Any]:
    """Convert a Protolink input schema into a JSON Schema object.

    Tool authors may provide either a full JSON Schema object or the flat
    parameter map generated by :mod:`protolink.tools.schema`. The returned
    schema is always an object with ``properties`` and ``required`` lists, which
    is the common denominator expected by OpenAI, Anthropic, Gemini, Ollama,
    llama.cpp servers, and OpenAI-compatible chat-completion APIs.
    """
    if not input_schema:
        return {"type": "object", "properties": {}, "required": [], "additionalProperties": False}

    if input_schema.get("type") == "object" or "properties" in input_schema:
        properties = dict(input_schema.get("properties", {}))
        required = list(input_schema.get("required", []))
        additional = input_schema.get("additionalProperties", False)
        return {
            "type": "object",
            "properties": properties,
            "required": required,
            "additionalProperties": additional,
        }

    properties: dict[str, Any] = {}
    required: list[str] = []
    for name, definition in input_schema.items():
        prop = dict(definition) if isinstance(definition, dict) else {"type": "string"}
        is_required = bool(prop.pop("required", True))
        if is_required:
            required.append(name)
        properties[name] = prop

    return {
        "type": "object",
        "properties": properties,
        "required": required,
        "additionalProperties": False,
    }


def build_runtime_tool_schemas(
    tools: dict[str, BaseTool],
    *,
    include_agent_tools: bool,
) -> dict[str, dict[str, Any]]:
    """Build JSON Schema objects for native provider tool declarations.

    The returned mapping contains the agent's local tools plus, when requested,
    two synthetic runtime tools for agent delegation. Those synthetic tools do
    not execute user code directly; they are normalized back into
    ``AgentCallAction`` objects so the normal Agent transport layer can resolve
    and dispatch the target agent.
    """
    schemas: dict[str, dict[str, Any]] = {
        name: normalize_tool_parameters(tool.input_schema or {}) for name, tool in tools.items()
    }

    if include_agent_tools:
        schemas[AGENT_INFER_TOOL_NAME] = {
            "type": "object",
            "additionalProperties": False,
            "properties": {
                "agent": {"type": "string", "description": "Registered target agent name."},
                "prompt": {"type": "string", "description": "Instruction for the target agent to infer over."},
            },
            "required": ["agent", "prompt"],
        }
        schemas[AGENT_TOOL_CALL_TOOL_NAME] = {
            "type": "object",
            "additionalProperties": False,
            "properties": {
                "agent": {"type": "string", "description": "Registered target agent name."},
                "tool": {"type": "string", "description": "Tool owned by the target agent."},
                "args_json": {
                    "type": "string",
                    "description": "JSON object string containing arguments for the target agent's tool.",
                },
            },
            "required": ["agent", "tool", "args_json"],
        }

    return schemas


def describe_runtime_tool(name: str, tools: dict[str, BaseTool]) -> str:
    """Return a concise description for a real or synthetic runtime tool."""
    if name == AGENT_INFER_TOOL_NAME:
        return "Delegate an inference request to another registered Protolink agent."
    if name == AGENT_TOOL_CALL_TOOL_NAME:
        return "Ask another registered Protolink agent to execute one of its tools."
    tool = tools.get(name)
    return getattr(tool, "description", "") or f"Execute the Protolink tool named {name}."


def openai_responses_tools(tools: dict[str, BaseTool], *, include_agent_tools: bool) -> list[dict[str, Any]]:
    """Build OpenAI Responses API function tool declarations."""
    schemas = build_runtime_tool_schemas(tools, include_agent_tools=include_agent_tools)
    return [
        {
            "type": "function",
            "name": name,
            "description": describe_runtime_tool(name, tools),
            "parameters": schema,
            "strict": False,
        }
        for name, schema in schemas.items()
    ]


def chat_completion_tools(tools: dict[str, BaseTool], *, include_agent_tools: bool) -> list[dict[str, Any]]:
    """Build Chat Completions-style function tool declarations."""
    schemas = build_runtime_tool_schemas(tools, include_agent_tools=include_agent_tools)
    return [
        {
            "type": "function",
            "function": {
                "name": name,
                "description": describe_runtime_tool(name, tools),
                "parameters": schema,
            },
        }
        for name, schema in schemas.items()
    ]


def anthropic_tools(tools: dict[str, BaseTool], *, include_agent_tools: bool) -> list[dict[str, Any]]:
    """Build Anthropic Messages API tool declarations."""
    schemas = build_runtime_tool_schemas(tools, include_agent_tools=include_agent_tools)
    return [
        {
            "name": name,
            "description": describe_runtime_tool(name, tools),
            "input_schema": schema,
        }
        for name, schema in schemas.items()
    ]


def gemini_function_declarations(tools: dict[str, BaseTool], *, include_agent_tools: bool) -> list[dict[str, Any]]:
    """Build Gemini function declarations using JSON schema parameters."""
    schemas = build_runtime_tool_schemas(tools, include_agent_tools=include_agent_tools)
    return [
        {
            "name": name,
            "description": describe_runtime_tool(name, tools),
            "parameters_json_schema": schema,
        }
        for name, schema in schemas.items()
    ]


def native_tool_call_to_action(name: str, args: dict[str, Any] | None) -> ToolCallAction | AgentCallAction:
    """Map a provider-native function/tool call into a Protolink action.

    Real tool names become ``ToolCallAction`` instances. The two reserved
    Protolink tool names become ``AgentCallAction`` instances. For delegated
    tool calls, the target tool's arguments are carried as ``args_json`` because
    provider tool schemas must be declared up front, while remote agent tool
    schemas are discovered dynamically at runtime and may differ per agent.
    """
    normalized_name = name.strip()
    if not normalized_name:
        raise ValueError("native tool call is missing a function/tool name")

    payload = args or {}
    if normalized_name == AGENT_INFER_TOOL_NAME:
        return AgentCallAction(
            agent=str(payload.get("agent", "")),
            action="infer",
            prompt=str(payload.get("prompt", "")),
        )
    if normalized_name == AGENT_TOOL_CALL_TOOL_NAME:
        raw_args = payload.get("args_json", "{}")
        try:
            parsed_args = json.loads(raw_args) if isinstance(raw_args, str) else raw_args
        except json.JSONDecodeError as exc:
            raise ValueError("args_json for protolink_call_agent_tool must be valid JSON") from exc
        if not isinstance(parsed_args, dict):
            raise ValueError("args_json for protolink_call_agent_tool must decode to a JSON object")
        return AgentCallAction(
            agent=str(payload.get("agent", "")),
            action="tool_call",
            tool=str(payload.get("tool", "")),
            args=parsed_args,
        )
    return ToolCallAction(tool=normalized_name, args=payload)


def parse_json_arguments(raw: Any) -> dict[str, Any]:
    """Parse provider function arguments into a dictionary with clear errors."""
    if raw is None:
        return {}
    if isinstance(raw, dict):
        return raw
    if isinstance(raw, str):
        if not raw.strip():
            return {}
        data = json.loads(raw)
        if not isinstance(data, dict):
            raise ValueError("tool arguments must decode to a JSON object")
        return data
    raise TypeError(f"tool arguments must be an object or JSON string, got {type(raw).__name__}")
