"""Public tool contracts, schema helpers, and opt-in built-in factories."""

from .base import BaseTool
from .builtins import (
    CalendarBackend,
    DatabaseBackend,
    EmailBackend,
    Gmail,
    GoogleAPIError,
    GoogleCalendar,
    GoogleToken,
    HTTPHeaders,
    IMAPEmail,
    MailBackendError,
    MailPassword,
    MicrosoftGraphError,
    OAuthToken,
    OutlookCalendar,
    OutlookEmail,
    SQLiteDatabase,
    UserInputHandler,
    UserInputRequest,
    UserInputResult,
    ask_user_tool,
    calculator,
    calendar_tools,
    current_datetime,
    database_tools,
    document_tools,
    email_tools,
    fetch_url,
    filesystem_tools,
    git_tool,
    http_tool,
    process_tool,
    shell_tool,
    storage_tools,
    web_search,
)
from .schema import infer_input_schema, infer_output_schema, normalize_schema, validate_tool_args
from .tool import ActionBuilder, Tool

__all__ = [
    "ActionBuilder",
    "BaseTool",
    "CalendarBackend",
    "DatabaseBackend",
    "EmailBackend",
    "Gmail",
    "GoogleAPIError",
    "GoogleCalendar",
    "GoogleToken",
    "HTTPHeaders",
    "IMAPEmail",
    "MailBackendError",
    "MailPassword",
    "MicrosoftGraphError",
    "OAuthToken",
    "OutlookCalendar",
    "OutlookEmail",
    "SQLiteDatabase",
    "Tool",
    "UserInputHandler",
    "UserInputRequest",
    "UserInputResult",
    "ask_user_tool",
    "calculator",
    "calendar_tools",
    "current_datetime",
    "database_tools",
    "document_tools",
    "email_tools",
    "fetch_url",
    "filesystem_tools",
    "git_tool",
    "http_tool",
    "infer_input_schema",
    "infer_output_schema",
    "normalize_schema",
    "process_tool",
    "shell_tool",
    "storage_tools",
    "validate_tool_args",
    "web_search",
]
