"""Public tool contracts, schema helpers, and opt-in built-in factories."""

from .base import BaseTool
from .builtins import (
    CalendarBackend,
    EmailBackend,
    Gmail,
    GoogleAPIError,
    GoogleCalendar,
    GoogleToken,
    IMAPEmail,
    MailBackendError,
    MailPassword,
    MicrosoftGraphError,
    OAuthToken,
    OutlookCalendar,
    OutlookEmail,
    UserInputHandler,
    UserInputRequest,
    UserInputResult,
    ask_user_tool,
    calculator,
    calendar_tools,
    current_datetime,
    email_tools,
    fetch_url,
    filesystem_tools,
    git_tool,
    process_tool,
    shell_tool,
    web_search,
)
from .schema import infer_input_schema, infer_output_schema, normalize_schema, validate_tool_args
from .tool import ActionBuilder, Tool

__all__ = [
    "ActionBuilder",
    "BaseTool",
    "CalendarBackend",
    "EmailBackend",
    "Gmail",
    "GoogleAPIError",
    "GoogleCalendar",
    "GoogleToken",
    "IMAPEmail",
    "MailBackendError",
    "MailPassword",
    "MicrosoftGraphError",
    "OAuthToken",
    "OutlookCalendar",
    "OutlookEmail",
    "Tool",
    "UserInputHandler",
    "UserInputRequest",
    "UserInputResult",
    "ask_user_tool",
    "calculator",
    "calendar_tools",
    "current_datetime",
    "email_tools",
    "fetch_url",
    "filesystem_tools",
    "git_tool",
    "infer_input_schema",
    "infer_output_schema",
    "normalize_schema",
    "process_tool",
    "shell_tool",
    "validate_tool_args",
    "web_search",
]
