import contextvars
import os
import uuid
from typing import Any

from protolink.models import Part, Task
from protolink.telemetry._deps import require_langfuse
from protolink.telemetry.base import Telemetry
from protolink.utils.logging import get_logger

logger = get_logger("protolink.telemetry.langfuse")

_current_langfuse_trace = contextvars.ContextVar("langfuse_trace", default=None)
_current_langfuse_generation = contextvars.ContextVar("langfuse_generation", default=None)
_current_langfuse_span = contextvars.ContextVar("langfuse_span", default=None)


class LangfuseTelemetry(Telemetry):
    """Langfuse implementation for Protolink telemetry.

    This class tracks agent tasks as traces, and LLM/Tool executions as spans or
    generations within those traces. It utilizes `contextvars` to manage the active
    trace and span states asynchronously, ensuring a non-invasive integration
    without the need to pass context objects through the execution chain.
    """

    def __init__(self, public_key: str | None = None, secret_key: str | None = None, host: str | None = None) -> None:
        """Initializes the Langfuse telemetry tracker.

        Args:
            public_key (str | None): The Langfuse public key. Defaults to the `LANGFUSE_PUBLIC_KEY` environment variable
            secret_key (str | None): The Langfuse secret key. Defaults to the `LANGFUSE_SECRET_KEY` environment variable
            host (str | None): The Langfuse API host URL. Defaults to `LANGFUSE_HOST` or "https://cloud.langfuse.com".

        Raises:
            ImportError: If the `langfuse` package is not installed.
        """
        _, langfuse = require_langfuse()

        self.langfuse = langfuse(
            public_key=public_key or os.environ.get("LANGFUSE_PUBLIC_KEY"),
            secret_key=secret_key or os.environ.get("LANGFUSE_SECRET_KEY"),
            host=host or os.environ.get("LANGFUSE_HOST", "https://cloud.langfuse.com"),
        )

    async def on_task_start(self, task: Task, agent_name: str) -> Any:
        """Starts a new Langfuse trace for the given task.

        Args:
            task (Task): The task being processed.
            agent_name (str): The name of the agent handling the task.

        Returns:
            Any: None.
        """
        try:
            trace = self.langfuse.trace(
                name=f"Task: {agent_name}",
                id=task.id if hasattr(task, "id") else str(uuid.uuid4()),
                metadata={"agent_name": agent_name},
            )
            _current_langfuse_trace.set(trace)
        except Exception as e:
            logger.warning(f"Failed to start Langfuse trace: {e}")

    async def on_task_end(self, task: Task, result: Task, agent_name: str) -> Any:
        """Ends the active Langfuse trace and logs the final output.

        Args:
            task (Task): The original task.
            result (Task): The completed task containing the output.
            agent_name (str): The name of the agent.

        Returns:
            Any: None.
        """
        trace = _current_langfuse_trace.get()
        if not trace:
            return
        try:
            trace.update(output=result.to_dict() if hasattr(result, "to_dict") else str(result))
            self.langfuse.flush()
        except Exception as e:
            logger.warning(f"Failed to end Langfuse trace: {e}")
        finally:
            _current_langfuse_trace.set(None)

    async def on_llm_start(self, prompt: str, model: str | None = None) -> Any:
        """Starts a new generation span within the active Langfuse trace.

        Args:
            prompt (str): The input prompt for the LLM.
            model (str | None): The model identifier.

        Returns:
            Any: None.
        """
        trace = _current_langfuse_trace.get()
        if not trace:
            return
        try:
            generation = trace.generation(
                name="LLM Call",
                model=model,
                input=prompt,
            )
            _current_langfuse_generation.set(generation)
        except Exception as e:
            logger.warning(f"Failed to start Langfuse LLM generation: {e}")

    async def on_llm_end(self, response: Part) -> Any:
        """Ends the active LLM generation span and logs the response.

        Args:
            response (Part): The response part generated by the LLM.

        Returns:
            Any: None.
        """
        generation = _current_langfuse_generation.get()
        if not generation:
            return
        try:
            output = response.content if hasattr(response, "content") else str(response)
            generation.end(output=output)
        except Exception as e:
            logger.warning(f"Failed to end Langfuse LLM generation: {e}")
        finally:
            _current_langfuse_generation.set(None)

    async def on_tool_start(self, tool_name: str, args: dict[str, Any]) -> Any:
        """Starts a new tool execution span within the active Langfuse trace.

        Args:
            tool_name (str): The name of the tool.
            args (dict[str, Any]): The arguments provided to the tool.

        Returns:
            Any: None.
        """
        trace = _current_langfuse_trace.get()
        if not trace:
            return
        try:
            span = trace.span(
                name=f"Tool: {tool_name}",
                input=args,
            )
            _current_langfuse_span.set(span)
        except Exception as e:
            logger.warning(f"Failed to start Langfuse tool span: {e}")

    async def on_tool_end(self, tool_name: str, result: Any, error: str | None = None) -> Any:
        """Ends the active tool span, logging the result or error.

        Args:
            tool_name (str): The name of the tool.
            result (Any): The output of the tool execution.
            error (str | None): Any error message if the tool failed.

        Returns:
            Any: None.
        """
        span = _current_langfuse_span.get()
        if not span:
            return
        try:
            if error:
                span.end(level="ERROR", status_message=error)
            else:
                span.end(output=result)
        except Exception as e:
            logger.warning(f"Failed to end Langfuse tool span: {e}")
        finally:
            _current_langfuse_span.set(None)
