import re

from protolink.client import AgentClient, RegistryClient
from protolink.discovery import Registry
from protolink.models import Task
from protolink.types import FlowTarget

from .base import Flow


class Router(Flow):
    """A flow step that enforces conditional branching based on LLM decision making.

    Instead of relying on a hardcoded Python condition function, the Router relies on Semantic Context Injection.
    When a Router is placed in a Pipeline, the Pipeline extracts the Router's `routing_prompt` and target options,
    injecting them into the preceding agent's system prompt. The preceding agent evaluates its own task context
    and appends a `[ROUTE: key]` tag to its final message. The Router parses this tag and forwards the task to
    the chosen destination.

    Routing destinations can be:
    - **Agent instances**: Local execution.
    - **URL strings**: Remote A2A execution.
    - **Nested Flows**: Sub-orchestration logic.
    """

    def __init__(
        self,
        routes: dict[str, FlowTarget],
        routing_prompt: str,
        client: AgentClient | None = None,
        registry: Registry | RegistryClient | None = None,
    ) -> None:
        """Initialize the dynamic LLM router.

        Args:
            routes: A dictionary mapping potential string conditions to their respective Agent, URLs, or nested Flows.
            routing_prompt: The instruction prompt that will be passed to the preceding agent to explain the criteria
                for selecting each route.
            client: Optional `AgentClient` for executing remote paths.
            registry: Optional registry configuration for discovery.
        """
        super().__init__(client=client, registry=registry)
        self.routes = routes
        self.routing_prompt = routing_prompt

    async def execute(self, task: Task) -> Task:
        """Execute the conditionally chosen branch.

        Parses the `[ROUTE: key]` tag generated by the preceding agent, removes it from the payload,
        and forwards the task.

        Args:
            task: The active `Task` state containing the preceding agent's output.

        Returns:
            The resulting `Task` object post-execution on the chosen route.

        Raises:
            ValueError: If the [ROUTE: key] tag is missing or maps to an undefined route.
        """
        last_content = str(task.get_last_part_content())

        # Regex to find [ROUTE: key] specifically at the end of the content or anywhere in it
        match = re.search(r"\[ROUTE:\s*([a-zA-Z0-9_-]+)\]", last_content)

        if not match:
            raise ValueError(
                f"Router could not find a valid [ROUTE: key] tag in the previous output.\n"
                f"Ensure the preceding agent follows the routing instructions.\n"
                f"Output was: {last_content}"
            )

        next_route_key = match.group(1)

        self._logger.info(f"Router evaluated LLM tag: routing to '{next_route_key}'")

        if next_route_key not in self.routes:
            raise ValueError(
                f"The preceding agent produced a route key '{next_route_key}' "
                f"which does not exist in mapped routes: {list(self.routes.keys())}"
            )

        # Clean the tag from the task so the downstream agent doesn't see it
        last_item = task.get_last_item()
        if last_item and last_item.parts:
            for part in last_item.parts:
                if part.type in ("text", "infer_output") and isinstance(part.content, str):
                    part.content = part.content.replace(match.group(0), "").strip()
                    break

        route_destination = self.routes[next_route_key]
        return await self._execute_target(route_destination, task)
