from typing import Any

from protolink.models import Part, Task
from protolink.telemetry.base import Telemetry


class MultiTelemetry(Telemetry):
    """Multiplexes telemetry events to multiple telemetry trackers.

    This allows agents to broadcast execution events to multiple telemetry
    trackers (e.g., Langfuse and Langsmith) simultaneously.
    """

    def __init__(self, trackers: list[Telemetry]) -> None:
        """Initializes the MultiTelemetry multiplexer.

        Args:
            trackers (list[Telemetry]): A list of Telemetry instances.
        """
        self.trackers = trackers

    async def on_task_start(self, task: Task, agent_name: str) -> Any:
        """Called when an agent starts processing a task.

        Args:
            task (Task): The task being processed.
            agent_name (str): The name of the agent processing the task.

        Returns:
            Any: None.
        """
        for tracker in self.trackers:
            await tracker.on_task_start(task, agent_name)

    async def on_task_end(self, task: Task, result: Task, agent_name: str) -> Any:
        """Called when an agent finishes processing a task.

        Args:
            task (Task): The original task.
            result (Task): The resulting task after processing.
            agent_name (str): The name of the agent processing the task.

        Returns:
            Any: None.
        """
        for tracker in self.trackers:
            await tracker.on_task_end(task, result, agent_name)

    async def on_llm_start(self, prompt: str, model: str | None = None) -> Any:
        """Called before making an inference call to an LLM.

        Args:
            prompt (str): The prompt being sent to the LLM.
            model (str | None): The name of the LLM model.

        Returns:
            Any: None.
        """
        for tracker in self.trackers:
            await tracker.on_llm_start(prompt, model)

    async def on_llm_end(self, response: Part) -> Any:
        """Called after an inference call to an LLM completes.

        Args:
            response (Part): The response part generated by the LLM.

        Returns:
            Any: None.
        """
        for tracker in self.trackers:
            await tracker.on_llm_end(response)

    async def on_tool_start(self, tool_name: str, args: dict[str, Any]) -> Any:
        """Called before executing a tool.

        Args:
            tool_name (str): The name of the tool.
            args (dict[str, Any]): The arguments provided to the tool.

        Returns:
            Any: None.
        """
        for tracker in self.trackers:
            await tracker.on_tool_start(tool_name, args)

    async def on_tool_end(self, tool_name: str, result: Any, error: str | None = None) -> Any:
        """Called after a tool execution completes.

        Args:
            tool_name (str): The name of the tool.
            result (Any): The result of the tool execution.
            error (str | None): The error message if the tool execution failed.

        Returns:
            Any: None.
        """
        for tracker in self.trackers:
            await tracker.on_tool_end(tool_name, result, error)
